name: 'Build Godot Project'
 
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, mac]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.4.1
        with:
          name: example
          preset: Web
          debugMode: "false"